---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 83809.
--- DateTime: 2025/10/10 19:25
---

-- 获取锁中线程表示
local id = redis.call('get', KEYS[1])

-- 判断是否与指定的标示（当前线程标示）一致
if(id == ARGV[1]) then
    -- 释放锁
    return redis.call('del', KEYS[1])
end

return 0